### ISSUE TITLE
some enhancements / bugs

### ISSUE THREAD

**Issue by mathcat4** [Vyxal/vyxal.github.io#10]
Here's a list of features (subjectively sorted by priority) which don't need separate issues:

### Medium priority
- [ ] make idioms tab scrollable
- [ ] Add basic mobile support (fancy css for resizing stuff, make tabs non-moveable and so on)
- [ ] Fix the compressor tab
- [ ] Syntax highlighting (once it's possible to do so)
- [x] Add hotkey support (ctrl-r for run, ...)
- [x] [The navbar clips off](https://i.imgur.com/Jm1zibK.png)
### Low priority
- [ ] Character substitution with tab (ideally list them somewhere too)
- [ ] Make the "Add tab" screen align more with the dark theme
- [ ] Add seperate tab for flags
- [ ] Make SBSCify operator also turn SBSC to literate code
- [ ] Tooltip for copy to clipboard / compress
- [ ] Option to select version (once versioning works)
- [x] [Fix padding](https://i.imgur.com/83pZUjU.png)

**Comment by mathcat4** [comment]
Feel free to remove / add tasks. (Most of the low-priority tasks were basically random shower thoughts :d)

**Comment by razetime** [comment]
what is the use of undo/redo buttons? `C-Z` and `C-Y` seem to work as always.

**Comment by mathcat4** [comment]
@razetime oops right got confused good point
