### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/vyxal.github.io#15]
**Describe the feature**

Show sugarless code in online interpreter.

**Details**
I see a few ways to go about implementing this.
- Add a flag to display sugarless code in the debug box.
- If sugar is included, automatically display sugarless code in the debug box.
- On execution, replace the contents of the code boxes with the sugarless code.
- (My personal favorite) Replace sugared code with sugarless as you type.

If we go with the last option, we could also incorporate it with syntax highlighting and have it mark invalid sugars and elements.

**Comment by gingershaped** [comment]
The interpreter rework I'm making does the last option (desugar as you type using CodeMirror's autocomplete), so this is planned and will be ready soon™

**Comment by ysthakur** [comment]
Replacing literate code with regular code would be nice, but it should be an option, since someone might want to look at the literate code, in which case you could have a separate box that displays the regular version of the literate code you're typing

**Comment by AMiller42** [comment]
I would think that if you are using the 'l' flag then it would keep the literate code

**Comment by a-a-GiTHuB-a-a** [comment]
Why is "ready soon" trademarked?

**Comment by AMiller42** [comment]
> Why is "ready soon" trademarked?

https://wowwiki-archive.fandom.com/wiki/Soon

**Comment by lyxal** [comment]
I was wondering why this wasn't working online until I realised it's being sent to scribe :p

```scala
sugarless match
    case Some(code) => scribe.debug(s"Sugarless: $code")
    case None => ()
```
