### ISSUE TITLE
Output tab doesn't have an arrow but still is clickable

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [Vyxal/vyxal.github.io#29]
The Vyxal 3 interpreter (in the latest version :>) is missing an arrow before the Output tab. Attached are two screenshots, both showing the issue and in conjunction proving clickability.
<img width="1121" alt="when output isn't open" src="https://github.com/Vyxal/vyxal.github.io/assets/64599476/a21c4c6e-8f30-4aaa-8616-1bdd5ae54bf7">
<img width="1122" alt="h" src="https://github.com/Vyxal/vyxal.github.io/assets/64599476/60990fc8-f694-4c47-a536-9037fc4f511c">

**Comment by gingershaped** [comment]
This will be fixed with the release of the New Interpreter

**Comment by a-a-GiTHuB-a-a** [comment]
Will this be closed when the PR for the New Interpreter™ is _created_ or _merged_?

**Comment by gingershaped** [comment]
> Will this be closed when the PR for the New Interpreter™ is _created_ or _merged_?

Does it matter? It's getting closed regardless :p

**Comment by lyxal** [comment]
> Will this be closed when the PR for the New Interpreter™ is _created_ or _merged_?

merged. I'll look into adding the detail arrow in the meantime to both v2 and v3 sites.

**Comment by lyxal** [comment]
So I did a little digging and this is because the detail summary is displayed as `inline-block` (intentional). That hides the arrow for some reason. The summary is required to be inline block, so this will have to be a wont-fix issue.

**Comment by a-a-GiTHuB-a-a** [comment]
Why not have a flex container for the copy button and output tab? Does that break anything?
